package domain

// ============================================================================
// NUTRITION MACRO TARGETS
// ============================================================================
// Two states only: training day and rest day.
// Phase does NOT change the numbers — only the copy/insights.
// This is backed by the 2025 GSSI review and BioCycle study.

// MacroTargets holds the calculated macro targets for a user.
type MacroTargets struct {
	TrainingDay DayMacros `json:"training_day"`
	RestDay     DayMacros `json:"rest_day"`
}

// DayMacros holds macro values for a single day type.
type DayMacros struct {
	Calories int     `json:"calories"`
	ProteinG float64 `json:"protein_g"`
	CarbsG   float64 `json:"carbs_g"`
	FatG     float64 `json:"fat_g"`
}

// HydrationInfo holds hydration targets for a single day.
type HydrationInfo struct {
	Liters          float64 `json:"liters"`
	Glasses         int     `json:"glasses"`
	ShowElectrolyte bool    `json:"show_electrolyte"`
	ShowCapNote     bool    `json:"show_cap_note,omitempty"`
}

// ============================================================================
// MEAL CONTENT — generated by LLM
// ============================================================================

// MealSlot represents a single meal in the day with options.
type MealSlot struct {
	MealName     string       `json:"meal_name"`
	TimingWindow string       `json:"timing_window"`
	IsPrePost    bool         `json:"is_pre_post,omitempty"`
	MacroTargets DayMacros    `json:"macro_targets"`
	Options      []MealOption `json:"options"`
	PhaseNote    *string      `json:"phase_note,omitempty"`
}

// MealOption represents one option for a meal slot.
type MealOption struct {
	Name        string           `json:"name"`
	Summary     string           `json:"summary"`
	Flag        *string          `json:"flag,omitempty"`
	FlagReason  *string          `json:"flag_reason,omitempty"`
	Ingredients []MealIngredient `json:"ingredients"`
	Macros      DayMacros        `json:"macros"`
}

// MealIngredient represents a single ingredient in a meal option.
type MealIngredient struct {
	Name    string  `json:"name"`
	AmountG float64 `json:"amount_g"`
	Approx  string  `json:"approx"`
}

// ============================================================================
// DAILY + WEEKLY NUTRITION PLAN
// ============================================================================

// NutritionWeekPlan is the complete weekly nutrition plan.
type NutritionWeekPlan struct {
	Phase   CyclePhase          `json:"phase"`
	Targets MacroTargets        `json:"targets"`
	Days    [7]NutritionDayPlan `json:"days"`
	Water   float64             `json:"water_base_liters"` // base without activity/phase

	// CopyEnriched is true once every meal option's Name/Summary has been
	// polished by the async copy-polish pipeline (see mealgen.EnrichPlanCopy)
	// — false means options may still show placeholder/raw text
	// (template name + comma-joined ingredients). Defaults to false on a
	// freshly generated or freshly re-solved plan (e.g. after a weight/
	// height edit triggers a nutrition recompute) since that produces new
	// raw copy that hasn't been enriched yet. The client can poll for this
	// flipping true instead of diffing text to know when to refresh.
	CopyEnriched bool `json:"copy_enriched"`
}

// NutritionDayPlan holds nutrition info for a single day of the week.
type NutritionDayPlan struct {
	Weekday       string        `json:"weekday"`
	IsTrainingDay bool          `json:"is_training_day"`
	Macros        DayMacros     `json:"macros"`
	Hydration     HydrationInfo `json:"hydration"`
	Meals         []MealSlot    `json:"meals,omitempty"`
}
